version: '3.8'

services:
  frontend:
    build: .
    container_name: frontend-app
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - ./public:/usr/share/nginx/html
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge